### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by evilangel009** [ideo/SketchContentSync.sketchplugin#1]
Tried downloading and installing the plugin. There seems to be a .sketchplugin file missing from the .zip file. Renaming the file extension to .sketchplugin does not work either.

**Comment by dbrody** [comment]
The github repo itself is the .sketchplugin file so renaming the zip file wont work. But unzipping it and then renaming it will.

To make it easier, here is a link to the zip of the github, when it is unzipped it should be the .sketchplugin file:
https://github.com/ideo/SketchContentSync.sketchplugin/releases/download/v0.2.1/SketchContentSync.sketchplugin.zip

**Comment by dbrody** [comment]
@evilangel009 Was this able to fix your trouble? Would like to know your feedback so we can improve the experience and close issues.

We've also now added a site for this repo to easily be able to download the sketchfile itself:
http://contentsync.io/

**Comment by evilangel009** [comment]
Yes, that worked. Thank you!
