### ISSUE TITLE
Doesn't work with multiple artboards

### ISSUE THREAD

**Issue by Joshuwar** [ideo/SketchContentSync.sketchplugin#14]
Hi there, I've noticed that this sync system doesn't seem to work across multiple artboards. 

For example if I have multiple 'sync:' fields on multiple artboards, and try to update them all, only the first artboard is sync'd. The rest remain as they were. Probably this has something to do with the recent Sketch update. 

Hope it's a simple fix! And thanks again for all the great work you've put into this already. 👍

**Comment by Joshuwar** [comment]
I've realised that actually the plugin works fine with multiple artboards, it's actually only crashing on the second artboard (and any subsequent ones) when there are symbol instances (anywhere in the document). So it's probably related to the same problem as my other issue... Sorry

**Comment by dbrody** [comment]
@Joshuwar Yes, seems to be an issue with the new Sketch version and how they handle symbols. I will be releasing a pretty big update soon.
