### ISSUE TITLE
Unable to fetch data

### ISSUE THREAD

**Issue by shamara26** [ideo/SketchContentSync.sketchplugin#2]
Whenever I try to sync from one of my Google spreadsheets, Sketch says it is unable to fetch the data. I can, however, sync from your test spreadsheet. I've checked and I'm using the same permissions as in the test spreadsheet.

Spreadsheet: https://docs.google.com/spreadsheets/d/1vrNNM5J60k-RKw8OII3S_UzceKFP0cCWUF0N8VCwVPU/edit#gid=0

**Comment by dbrody** [comment]
I think you need to export the sheet for web or something. I'll check when I'm back at my computer.

**Comment by dbrody** [comment]
Yes, you need to make sure to publish you google document to the web. To do so, in the google doc, go to 'File' -> 'Publish to the Web...' then 'Publish'.

**Comment by dbrody** [comment]
@shamara26 Were you able to get this working?

**Comment by shamara26** [comment]
Yeah, I was. Any plans on doing a version where you don't have to publish the sheet? I'm using this for work, and the spreadsheets are for our private use.

**Comment by dbrody** [comment]
We have some small discussions around connecting to and/or making a platform for that purpose. Would allow for more custom and use case specific features for Sketch. Would something like that address your need?

**Comment by dbrody** [comment]
I'm moving the rest of this conversation to a separate issue / feature.
