### ISSUE TITLE
Where is .sketchplugin file?

### ISSUE THREAD

**Issue by monicameika** [ideo/SketchContentSync.sketchplugin#3]
When I download it, there is no any .sketchplugin file :(

**Comment by dbrody** [comment]
Yes, the github repo itself is the .sketchplugin file.

Here is a link to the zip of the github, when it is unzipped it should be the .sketchplugin file:
https://github.com/ideo/SketchContentSync.sketchplugin/releases/download/v0.2.1/SketchContentSync.sketchplugin.zip

**Comment by monicameika** [comment]
I got it! Thanks :)

**Comment by dbrody** [comment]
Great!
