### ISSUE TITLE
Override symbols content

### ISSUE THREAD

**Issue by jxalvarado88** [ideo/SketchContentSync.sketchplugin#5]
To improve the productivity and scalability of the designs we usually turn module assets into symbols, e.g. buttons, these can be used in different screens with different labels overriding the original... can the symbol layer name be the trigger to override the content instead of the actual text layer inside the symbol?

**Comment by jxalvarado88** [comment]
This same thing happens when symbols have more than 1 value to override, probably, naming the parent and giving the respective name to the text layers, so in the google sheet all of the content can be overwritten if parent name is the same...

**Comment by custa1200** [comment]
I think this is super important as far as my Sketch workflow goes. Love the idea of this plugin, I assume there would have to be some work from Bohemian to make this happen.

**Comment by dbrody** [comment]
I think that should be doable, the Sketch API is very extensible.

Can you explain the use cases and desired functionality a bit more in details?  Sounds like overriding the content of symbols is desired - does the current naming scheme for text work or are you wanting more to switch more than just text?

**Comment by lloydhumphreys** [comment]
+1 for this!

**Comment by hanonno** [comment]
+1!!

Love this idea, but I also use symbols a lot. 

For me ideal would be:

![sync goals](https://cloud.githubusercontent.com/assets/5139/18388076/6559a89e-76a0-11e6-91b7-84f87d4b03bd.png)

- I've created a symbol called title (just a label)
- In overrides I've put the key

Now when syncing the override should be updated. 

Keep up the great work!

**Comment by k0mrad** [comment]
+1 We need to have this implemented before my team could use sync as all of our buttons/form elements/components are symbol based.

**Comment by custa1200** [comment]
I think the design would work @dbrody. Really need this for symbol overrides.

**Comment by dbrody** [comment]
Thank you all for the great feedback.

Unfortunately the Sketch Plugin API is limited at the moment for symbols. I'm reaching out to them for additional feedback to see if there is a way to get access to the needed attributes to make this feature work. I will keep this thread updated.

**Comment by dbrody** [comment]
@jxalvarado88 @custa1200 @lloydhumphreys @hanonno @k0mrad 

Hi all, I have updated the plugin to V0.3.1. This version supports symbol overriding. It needed to be implemented a bit different than originally discussed on this thread. Let me know what you all think - I would love to hear your feedback.

See the updated readme section in reference to this feature here:
https://github.com/ideo/SketchContentSync.sketchplugin/blob/master/docs/symbols.md

226c664f3136cadac64cb273bb12a17243bd759e

**Comment by custa1200** [comment]
Hey @dbrody I could not get this to work with a Sketch 40.3 file :(

**Comment by dbrody** [comment]
@custa1200 I'm going to close this issue as the feature has a preliminary implementation. Can you please open a new issue with some details on your use case? Also, see if the Console app has any output from Sketch after running the plugin. If a software error occured, that may provide insight. Thanks!

**Comment by hanonno** [comment]
Hey @dbrody works as advertised, thanks a lot. We're going to try and integrate this into our workflow for our next project. 

Two things I noticed:

- Would be great to add support for nested symbols
- Some way to support images could be interesting

Is it alright if I make issues for those?

**Comment by dbrody** [comment]
Thank you for the feedback @hanonno ! Yes, please add a separate feature request issue for each feature request. Thank you again for your support and interest.
