### ISSUE TITLE
How to install? where is .sketchplugin??

### ISSUE THREAD

**Issue by sogen** [ideo/SketchContentSync.sketchplugin#7]
Hi and sorry, dumb question: 
Where's the .sketchplugin file?

**Comment by miralina** [comment]
@sogen Rename "SketchContentSync.sketchplugin-master.zip" to "SketchContentSync.sketchplugin", Then run that file and it will install. :)

**Comment by sogen** [comment]
Thanks @miralina, figured that out lol , 
but if anyone downloads the plugin using Safari it's very confusing since Safari automatically extracts the .zip file to a folder **and deletes the .zip file** 
👎 damn you Safari!

**Comment by dbrody** [comment]
Thanks all, I've updated the README to better explain how to install. Hope that helps :)
