### ISSUE TITLE
No actions in the plugin's menu

### ISSUE THREAD

**Issue by ludovicriffault** [ideo/SketchContentSync.sketchplugin#8]
Hi,

I've successfully installed the plugin but when I try to reach the "Google sync" item in the plugin's menu it fails, the list is empty and I can't go further than this screenshot:

![image](https://cloud.githubusercontent.com/assets/1585885/18313061/03cc70dc-750d-11e6-8388-9102407b777e.png)

Any ideas?

(I'm on Sketch 39.1 (31720))

**Comment by dbrody** [comment]
That is strange - I can verify I am on the same Sketch version and the menu loads for me.

Try to re-download / install the plugin. If that doesnt work, try to do it again and see if you get any error messages appearing for you in the Console application.

To confirm, you are getting the 'SketchContentSync' menu item but there are no sub menu items?

**Comment by ludovicriffault** [comment]
Yes I'm getting the 'SketchContentSync' menu item but it's empty

**Comment by ludovicriffault** [comment]
Just to be sure about the install procedure:
- I downloaded the zip file and get "SketchContentSync.sketchplugin-master.zip" which I rename to "SketchContentSync.sketchplugin"
- I double click on that file and I have a window that says "Successfully installed..."
- I open Sketch and the item is in the plugins menu but still empty

**Comment by dave-hiddendepth** [comment]
Same here. Installed fine but empty menu under Plugins > SketchContentSync > empty

**Comment by sogen** [comment]
@ludovicriffault no, you need to unzip the .zip file, not rename it.

**Comment by dave-hiddendepth** [comment]
When I click download it does not download a zip file?
File is named SketchContentSync.sketchplugin

**Comment by dbrody** [comment]
@dave-hiddendepth Where are you downloading it from?

Try downloading it from the [v0.2.1 Release](https://github.com/ideo/SketchContentSync.sketchplugin/releases/tag/v0.2.1)

**Comment by dave-hiddendepth** [comment]
Tried downloading the Source code (zip) file and didn't work.

Downloaded the SketchContentSync.sketchplugin.zip and got a warning from Chrome about file extension. Selected use .zip and then unzipped and installed, and working.
 
<img width="544" alt="screen shot 2016-09-08 at 23 21 58" src="https://cloud.githubusercontent.com/assets/1297728/18369031/1e392294-761b-11e6-87d5-c8d14857f766.png">

**Comment by ludovicriffault** [comment]
Yes! The solution of @dave-hiddendepth works perfectly but is

**Comment by sogen** [comment]
Why not just put everything inside a folder? 
That way if the person is using Safari, they will get a folder and the .sketchplugin inside, 

And if using Chrome or Firefox, they will get a .zip file, that, when unzipped, will also have a folder, with the .sketchplugin file inside.
